const ADD_TASK='tasks/ADD_NEW_TASK';
const REMOVE_TASK='tasks/REMOVE_TASK';
const LOAD_STORAGE='tasks/LOAD_FROM_STORAGE';
const UPDATE_LIST='tasks/UPDATE_LIST'

export default {ADD_TASK,REMOVE_TASK,LOAD_STORAGE,UPDATE_LIST}